#!/bin/bash

./lem_in < test/disjoint_map >> file
./lem_in < test/gen_big_0 >> file
./lem_in < test/gen_big_1 >> file
./lem_in < test/gen_big_2 >> file
./lem_in < test/gen_big_3 >> file
./lem_in < test/gen_flow_one_0 >> file
./lem_in < test/gen_flow_one_1 >> file
./lem_in < test/gen_flow_one_2 >> file
./lem_in < test/gen_flow_one_3 >> file
./lem_in < test/gen_flow_thousand_0 >> file
./lem_in < test/gen_flow_thousand_1 >> file
./lem_in < test/gen_flow_thousand_2 >> file
./lem_in < test/gen_flow_thousand_3 >> file
./lem_in < test/gen_superposition_0 >> file
./lem_in < test/gen_superposition_1 >> file
./lem_in < test/gen_superposition_2 >> file
./lem_in < test/gen_superposition_3 >> file
./lem_in < test/gen_superposition_4 >> file
./lem_in < test/test_bottleneck_0 >> file
./lem_in < test/test_bottleneck_1 >> file
./lem_in < test/test_connected_graph >> file
./lem_in < test/test_example >> file
./lem_in < test/test_example_0 >> file
./lem_in < test/test_input_0 >> file
./lem_in < test/test_input_subject_0 >> file
./lem_in < test/test_input_subject_1 >> file
./lem_in < test/test_input_subject_2-1 >> file
./lem_in < test/test_input_subject_2-2 >> file
./lem_in < test/test_input_subject_3 >> file
./lem_in < test/map_big_sup_1 >> file
./lem_in < test/map_big_sup_10 >> file
./lem_in < test/map_big_sup_11 >> file
./lem_in < test/map_big_sup_12 >> file
./lem_in < test/map_big_sup_13 >> file
./lem_in < test/map_big_sup_14 >> file
./lem_in < test/map_big_sup_15 >> file
./lem_in < test/map_big_sup_16 >> file
./lem_in < test/map_big_sup_17 >> file
./lem_in < test/map_big_sup_18 >> file
./lem_in < test/map_big_sup_19 >> file
./lem_in < test/map_big_sup_2 >> file
./lem_in < test/map_big_sup_20 >> file
./lem_in < test/map_big_sup_21 >> file
./lem_in < test/map_big_sup_22 >> file
./lem_in < test/map_big_sup_23 >> file
./lem_in < test/map_big_sup_24 >> file
./lem_in < test/map_big_sup_25 >> file
./lem_in < test/map_big_sup_26 >> file
./lem_in < test/map_big_sup_27 >> file
./lem_in < test/map_big_sup_28 >> file
./lem_in < test/map_big_sup_29 >> file
./lem_in < test/map_big_sup_3 >> file
./lem_in < test/map_big_sup_30 >> file
./lem_in < test/map_big_sup_4 >> file
./lem_in < test/map_big_sup_5 >> file
./lem_in < test/map_big_sup_6 >> file
./lem_in < test/map_big_sup_7 >> file
./lem_in < test/map_big_sup_8 >> file
./lem_in < test/map_big_sup_9 >> file
